### ISSUE TITLE
are old pr's from altassian considered to be incorporated?

### ISSUE THREAD

**Issue by wibed** [react-forked/dnd#195]
### Description
Add existing pr's from altassian to the codebase. 
i am looking forward especially to this one. which should improve ux for differently sized draggables on droppables

https://github.com/atlassian/react-beautiful-dnd/pull/2291

**Comment by 100terres** [comment]
> i am looking forward especially to this one. which should improve ux for differently sized draggables on droppables

PRs are more than welcome and I’ll try my best to review them, have discussions and see how new features could be integrated to the library, but I’ll try to follow a similar approach as the original maintainer of `react-beautiful-dnd` had. Here’s [a blog post](https://dev.to/alexandereardon/what-does-react-beautiful-dnd-cost-to-maintain-52e8) that explains how he was maintaining the repo.

> are old pr's from altassian considered to be incorporated?

That’s a good question! In the upcoming weeks, I’ll work on the roadmap to let everyone know what features will be prioritized. Since we have migrated the codebase [from Flow to TypeScript](https://github.com/react-forked/dnd/issues/8), all opened PRs on the atlassian repo would require refactoring to work with TypeScript, but based on the roadmap, I might base some feature from opened PRs on the atlassian repo. :slightly_smiling_face:
